import { AppNavigation } from "@/components/AppNavigation";
import { Button } from "@/components/ui/button";
import { downloadLandingPageHtml } from "@/lib/landingPageExport";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, CheckCircle2, Download, FilePenLine, Lightbulb, LoaderCircle, Rocket } from "lucide-react";
import React, { useMemo, useState } from "react";
import { useLocation, useRoute } from "wouter";

export default function SavedLandingPreview() {
  const [, params] = useRoute("/landing/:savedBlueprintId/preview");
  const [, setLocation] = useLocation();
  const savedBlueprintId = Number(params?.savedBlueprintId);
  const savedBlueprints = trpc.blueprint.list.useQuery();
  const record = useMemo(() => savedBlueprints.data?.find(item => item.id === savedBlueprintId), [savedBlueprints.data, savedBlueprintId]);
  const [ctaComplete, setCtaComplete] = useState(false);

  if (savedBlueprints.isLoading) return <main className="min-h-screen bg-slate-50"><AppNavigation /><div className="grid min-h-[calc(100vh-72px)] place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-blue-600" /></div></main>;
  if (!record) return <main className="min-h-screen bg-slate-50"><AppNavigation /><div className="grid min-h-[calc(100vh-72px)] place-items-center p-6"><section className="max-w-md rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><Rocket className="mx-auto h-8 w-8 text-blue-600" /><h1 className="mt-4 text-2xl font-black text-slate-950">Landing page unavailable.</h1><p className="mt-3 text-sm leading-6 text-slate-600">This saved venture is unavailable, or you do not have access to it.</p><Button onClick={() => setLocation("/dashboard")} className="mt-6 rounded-full bg-slate-950 text-white">Back to dashboard</Button></section></div></main>;
  const page = record.blueprint.landingPage;
  return <main className="min-h-screen bg-slate-50 text-slate-950"><AppNavigation /><header className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-6 py-5"><div className="flex items-center gap-2 text-sm font-black tracking-[-0.02em]"><Rocket className="h-4 w-4 text-blue-600" />{record.blueprint.startupName}</div><div className="flex gap-2"><Button type="button" variant="outline" onClick={() => setLocation(`/landing/${savedBlueprintId}/edit`)} className="rounded-full border-slate-200 bg-white text-xs"><FilePenLine className="h-3.5 w-3.5" />Edit</Button><Button type="button" variant="outline" onClick={() => downloadLandingPageHtml({ startupName: record.blueprint.startupName, landingPage: page })} className="rounded-full border-slate-200 bg-white text-xs"><Download className="h-3.5 w-3.5" />Export HTML</Button><Button type="button" variant="outline" onClick={() => setLocation("/dashboard")} className="rounded-full border-slate-200 bg-white text-xs"><ArrowLeft className="h-3.5 w-3.5" />Dashboard</Button></div></header><section className="mx-auto max-w-6xl px-6 pb-16 pt-12 text-center sm:pt-20"><p className="text-[11px] font-bold uppercase tracking-[0.22em] text-blue-600">Saved venture landing page</p><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-black tracking-[-0.055em] text-black sm:text-6xl">{page.heroHeadline}</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">{page.heroSubheadline}</p><Button type="button" onClick={() => setCtaComplete(true)} className="mt-9 h-12 rounded-full bg-blue-600 px-6 text-sm font-bold text-white shadow-[0_12px_28px_rgba(37,99,235,0.24)] hover:bg-blue-700">{ctaComplete ? "Thanks — we will be in touch" : page.ctaButtonText}<ArrowRight className="h-4 w-4" /></Button>{ctaComplete ? <p role="status" className="mt-4 flex items-center justify-center gap-2 text-sm font-medium text-emerald-700"><CheckCircle2 className="h-4 w-4" />CTA interaction recorded in this preview.</p> : null}</section><section className="mx-auto grid max-w-6xl gap-5 px-6 pb-20 md:grid-cols-3">{page.features.map((feature, index) => <article key={`${feature.title}-${index}`} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><Lightbulb className="h-5 w-5 text-amber-500" /><h2 className="mt-7 text-xl font-black tracking-[-0.025em] text-black">{feature.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{feature.description}</p></article>)}</section></main>;
}
